POST https://api2.keybexpress.com/api/register HTTP/1.1
Content-Type: application/json

{
    "name":"admin",
    "email":"admin@gmail.com",
    "password":"Sony@77"
}


####
POST http://127.0.0.1:8000/api/login HTTP/1.1
Content-Type: application/json

{
    "email":"ocph23@gmail.com",
    "password":"Sony@77"
}



####
Get http://127.0.0.1:8000/api/penjualan/stt/100001 HTTP/1.1
Content-Type: application/json



####
Get http://127.0.0.1:8000/api/penjualan/date/9/2022 HTTP/1.1
Content-Type: application/json